'use strict';var Aegis=function(selector){if(typeof selector=="string")this.collection=document.querySelectorAll(selector);else if(typeof selector=="object")if(selector.length>=1)this.collection=selector;else this.collection=[selector];else return null};Aegis.prototype.hide=function(){for(var i=0;i<this.collection.length;i++)this.collection[i].display="none"};Aegis.prototype.show=function(){for(var i=0;i<this.collection.length;i++)this.collection[i].display="block"};
Aegis.prototype.addClass=function(newClass){for(var i=0;i<this.collection.length;i++)this.collection[i].classList.add(newClass)};Aegis.prototype.removeClass=function(oldClass){for(var i=0;i<this.collection.length;i++)this.collection[i].classList.remove(oldClass)};Aegis.prototype.toggleClass=function(classes){classes=classes.split(" ");for(var i=0;i<this.collection.length;i++)for(var j=0;j<classes.length;j++)this.collection[i].classList.toggle(classes[j])};
Aegis.prototype.value=function(value){if(typeof value==="undefined")return this.collection[0].value;else this.collection[0].value=value};Aegis.prototype.click=function(callback){for(var i=0;i<this.collection.length;i++)this.collection[i].addEventListener("click",callback,false)};Aegis.prototype.submit=function(callback){for(var i=0;i<this.collection.length;i++)this.collection[i].addEventListener("submit",callback,false)};
Aegis.prototype.scroll=function(callback){for(var i=0;i<this.collection.length;i++)this.collection[i].addEventListener("scroll",callback,false)};Aegis.prototype.on=function(event,callback){for(var i=0;i<this.collection.length;i++)this.collection[i].addEventListener(event,callback,false)};Aegis.prototype.filter=function(element){return new Aegis(this.collection[0].querySelector(element))};
Aegis.prototype.data=function(name,value){if(typeof value==="undefined")return this.collection[0].dataset[name];else this.collection[0].dataset[name]=value};Aegis.prototype.text=function(value){if(typeof value==="undefined")return this.collection[0].textContent;else this.collection[0].textContent=value};Aegis.prototype.html=function(value){if(typeof value==="undefined")return this.collection[0].innerHTML;else this.collection[0].innerHTML=value};
Aegis.prototype.append=function(data){this.collection[0].innerHTML+=data};Aegis.prototype.each=function(callback){for(var i=0;i<this.collection.length;i++)callback(this.collection[i])};Aegis.prototype.get=function(index){return this.collection[index]};Aegis.prototype.isVisible=function(){return this.collection[0].display!="none"&&this.collection[0].offsetWidth>0&&this.collection[0].offsetHeight>0};Aegis.prototype.parent=function(){return new Aegis(this.collection[0].parentElement)};
Aegis.prototype.find=function(selector){return new Aegis(this.collection[0].querySelectorAll(selector))};Aegis.prototype.closest=function(searchSelector){var element=this.find(searchSelector);while(element){if(element.get(0)!=null)return element;element=this.parent().find(searchSelector)}return null};Aegis.prototype.attribute=function(attribute,value){if(typeof value==="undefined")this.collection[0].getAttribute(attribute);else return this.collection[0].setAttribute(attribute,value)};
function $_(selector){if(typeof selector!="undefined")return new Aegis(selector);else return Aegis}function $_ready(callback){window.addEventListener("load",callback)}var Router=function(){this.domain=window.location.hostname;this.routes=new Object};Router.prototype.getRoute=function(){return window.location.pathname.substring(0,window.location.pathname.length-1)};Router.prototype.getBaseUrl=function(){return this.domain};
Router.prototype.getFullUrl=function(){return window.location.href.substring(0,window.location.href.length-1)};Router.prototype.registerRoute=function(route,view){this.routes[route]=view};Router.prototype.getRoutes=function(){return this.routes};Router.prototype.match=function(){return typeof this.routes[this.getRoute()]!="undefined"||typeof this.routes[this.getRoute()]+"/"!="undefined"};Router.prototype.getView=function(){return this.routes[this.getRoute()]};Router.prototype.getProtocol=function(){return window.location.protocol};
Router.prototype.listen=function(){if(this.match())this.routes[this.getRoute()].show()};var Screen=function(){};Screen.isRetina=function(){return window.devicePixelRatio>=2};Screen.isPortrait=function(){return window.innerHeight>window.innerWidth};Screen.isLandscape=function(){return window.orientation===90||window.orientation===-90};Screen.getOrientation=function(){return this.isPortrait?"Portrait":"Landscape"};Screen.getMaximumWidth=function(){return window.screen.availWidth};
Screen.getMaxiumHeight=function(){return window.screen.availHeight};var Storage=function(){};Storage.get=function(key){if(window.localStorage)return localStorage.getItem(key);else console.warn("Your browser does not support Local Storage")};Storage.set=function(key,value){if(window.localStorage)localStorage.setItem(key,value);else console.warn("Your browser does not support Local Storage")};Storage.clear=function(){if(window.localStorage)ocalStorage.clear();else console.warn("Your browser does not support Local Storage")};
var Text=function(){};Text.capitalize=function(text){return text.charAt(0).toUpperCase()+text.slice(1)};Text.getSuffix=function(text,key){var suffix="";var position=text.indexOf(key);if(position!=-1){position+=key.length;suffix=text.substr(position,text.length-position)}return suffix};Text.getPrefix=function(text,key){var prefix="";var position=text.indexOf(key);if(position!=-1)prefix=text.substr(0,position);return prefix};
Text.toBinary=function(text){text=text.trim();if(!isNaN(text)){text=parseInt(text);var binary=bin.toString(2).replace(/(.{4})/g,"$1 ");return binary}else{var PADDING="00000000";var resultArray=[];for(var i=0;i<bin.length;i++){var compact=bin.charCodeAt(i).toString(2);var padded=compact.substring(0,PADDING.length-compact.length)+compact;resultArray.push(padded)}return resultArray.join(" ")}};
Text.toHexadecimal=function(text){text=text.trim();if(!isNaN(text)){text=parseInt(text);return text.toString(16).toUpperCase().replace(/(.{4})/g,"$1 ")}};Text.buildText=function(array,wrapper){var result="";if(array[0]){for(var i in array)result+=Text.buildText(array[i],wrapper);return result}else{var string=wrapper;for(var i$0 in array)string=string.replace(new RegExp("@"+i$0,"g"),array[i$0]);return string}};
Text.removeSpecialCharacters=function(text){var special=Array("#",":","\u00f1","\u00ed","\u00f3","\u00fa","\u00e1","\u00e9","\u00cd","\u00d3","\u00da","\u00c1","\u00c9","(",")","\u00a1","\u00bf","/");var common=Array("","","n","i","o","u","a","e","I","O","U","A","E","","","","","");for(var character in special)text=text.replace(new RegExp(special[character],"g"),common[character]);return text};
Text.removePunctuation=function(text){var special=new Array(";",",",".");for(var character in special)text=text.replace(new RegExp(special[character],"g"),"");return text};
Text.toFriendlyUrl=function(text){var expressions={"[\u00e1\u00e0\u00e2\u00e3\u00aa\u00e4]":"a","[\u00c1\u00c0\u00c2\u00c3\u00c4]":"A","[\u00cd\u00cc\u00ce\u00cf]":"I","[\u00ed\u00ec\u00ee\u00ef]":"i","[\u00e9\u00e8\u00ea\u00eb]":"e","[\u00c9\u00c8\u00ca\u00cb]":"E","[\u00f3\u00f2\u00f4\u00f5\u00ba\u00f6]":"o","[\u00d3\u00d2\u00d4\u00d5\u00d6]":"O","[\u00fa\u00f9\u00fb\u00fc]":"u","[\u00da\u00d9\u00db\u00dc]":"U","\u00e7":"c","\u00c7":"C","\u00f1":"n","\u00d1":"N","_":"-","[\u2019\u2018\u2039\u203a<>']":"",
'[\u201c\u201d\u00ab\u00bb\u201e"]':"","[(){}[]]":"","[?\u00bf!\u00a1#$%&^*\u00b4`~/\u00b0|]":"","[,.:;]":""," ":"-"};for(var regex in expressions)text=text.replace(new RegExp(regex,"g"),expressions[regex]);return text};Text.toUrl=function(text){return encodeURI(text)};var View=function(view,data){this.view=document.querySelector(view);this.viewContent=this.view.innerHTML;this.data=typeof data=="undefined"?null:data};View.prototype.getView=function(){return this.view};
View.prototype.isCompilable=function(){return this.data!=null};View.prototype.compile=function(){if(isCompilable){var compiledView=this.viewContent;for(var i in data)compiledView=compiledView.replace(new RegExp("{{"+i+"}}","g"),data[i]);this.view.innerHTML=compiledView}};View.prototype.show=function(){document.querySelector("[data-view].active").classList.remove("active");this.view.classList.add("active")};
